=== emigsm/booksAPI/src/main/resources/schemas/books-schema-input.json
{
        "$schema": "http://json-schema.org/draft-04/schema#",
        "properties": {
            "author": {
                "type": "string"
            },
            "id": {
                "type": "integer"
            },
            "pages": {
                "type": "integer"
            },
            "title": {
                "type": "string"
            }
        },
        "required": [
            "id",
            "author",
            "pages",
            "title"
        ],
        "type": "object"
    }

=== emigsm/booksAPI/src/main/resources/examples/books-example.json
[
	{
		"title":"Full dark no stars",
    	"author":"Stephen King",
    	"pages":438,
    	"id":1
	},
	{
		"title":"The silmarillion",
    	"author":"J.R.R Tolkien",
    	"pages":365,
    	"id":2
	},
	{
		"title":"The call of Cthulhu and other weird stories",
    	"author":"H.P. Lovecraft",
    	"pages":438,
    	"id":3
	},
	{
		"title":"The dark tower: The gunslinger",
    	"author":"Stephen King",
    	"pages":224,
    	"id":4
	}
]
